### ISSUE TITLE
My GitHub site misID'd as obscene

### ISSUE THREAD

**Issue by kenneth558** [JKomskis/Website#62]
How about you add ability to discern between religious use of "hell" and obscene use.  Thank you.
https://github.com/kenneth558/Dysusing-dispensation-no-more

**Comment by JKomskis** [comment]
The project is quite naive in finding "obscene commits". It is just a simple word match. I have a way of manually excluding repos, so I can add yours to the list as a stopgap solution.

Part of the fun of the project I felt was seeing false positives come up sometimes. Discerning between religious and obscene uses of "hell" or other words is a very interesting problem. Unfortunately, I don't have the skills or the bandwidth to develop such a solution. If you have any ideas PRs are always welcome.
